In [2]:
import pandas as pd
import numpy as np
adv=pd.read_csv('advt1.csv')
cov_matrix=np.cov(adv, rowvar=False, bias=True)
print(cov_matrix)

[[7334.09514375   69.51318     105.389855  ]
 [  69.51318     219.325604    113.924494  ]
 [ 105.389855    113.924494    471.936784  ]]


In [8]:
eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)
print(eigenvalues)
print(eigenvectors)

[ 175.43437921  513.49624282 7336.42690971]
[[ 0.00380577 -0.01807077 -0.99982947]
 [-0.93391214  0.35736234 -0.01001377]
 [ 0.35748236  0.93379098 -0.01551648]]


In [13]:
sorted_index = np.argsort(eigenvalues)[::-1]
sorted_eigenvalues = eigenvalues[sorted_index]
sorted_eigenvectors = eigenvectors[:,sorted_index]
print(sorted_eigenvalues)
print(sorted_eigenvectors)

[7336.42690971  513.49624282  175.43437921]
[[-0.99982947 -0.01807077  0.00380577]
 [-0.01001377  0.35736234 -0.93391214]
 [-0.01551648  0.93379098  0.35748236]]


In [14]:
num_components=3
eigenvector_subset = sorted_eigenvectors[:,0:num_components]
print(eigenvector_subset)

[[-0.99982947 -0.01807077  0.00380577]
 [-0.01001377  0.35736234 -0.93391214]
 [-0.01551648  0.93379098  0.35748236]]


In [16]:
    X_meaned=adv-np.mean(adv,axis=0)
    X_reduced = np.dot(eigenvector_subset.transpose() , X_meaned.transpose() ).transpose()
    print(X_reduced)


[[-8.37885459e+01  3.97809922e+01  5.56013765e-01]
 [ 1.02138730e+02  2.11666084e+01 -1.01665294e+01]
 [ 1.28992484e+02  4.66162737e+01 -7.78317392e+00]
 [-5.07097169e+00  3.24605596e+01 -6.83687316e+00]
 [-3.40590034e+01  2.09381554e+01  2.17232077e+01]
 [ 1.37372550e+02  5.31645709e+01 -8.57960991e+00]
 [ 8.95411919e+01 -1.56105218e+00 -1.17682445e+01]
 [ 2.71687122e+01 -1.85233852e+01 -3.45602280e+00]
 [ 1.39089396e+02 -3.26587125e+01  8.67340312e+00]
 [-5.23964374e+01 -1.70725851e+01  1.61552531e+01]
 [ 8.12021689e+01 -1.07115904e+01  1.37303504e+01]
 [-6.72413078e+01 -2.57554904e+01 -9.92245722e+00]
 [ 1.22554515e+02  3.94626040e+01  1.11275520e+00]
 [ 5.00532789e+01 -2.65102072e+01  6.09160958e+00]
 [-5.73839300e+01  1.68358060e+01 -3.26035737e+00]
 [-4.89406812e+01  2.87251422e+01 -1.46487389e+01]
 [ 7.78006550e+01  8.41188799e+01  1.70742421e+01]
 [-1.34889902e+02  2.69844146e+01 -5.72005587e+00]
 [ 7.80470423e+01 -1.10237502e+01 -2.09550601e+00]
 [-8.60991305e-02 -1.04730127e+